language: generic

dist: trusty
sudo: required

services:
  - docker

matrix:
    include:
    - env: JDK=8
    - env: JDK=9


before_install:
  - docker pull maven:3-jdk-${JDK}

script:
  - echo "**** Building JDK ${JDK} ****"
  - docker run -v ${PWD}:/mnt -it ${DOCKER_IMG}/${COMPILER} /bin/bash -c "cd /mnt; script/ci_build.sh"
