language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images/openjdk"

matrix:
    include:
    - env: JDK=8
    - env: JDK=9


before_install:
  - docker pull ${DOCKER_IMG}-${JDK}-maven:latest

script:
  - docker run -v ${PWD}:/mnt -it ${DOCKER_IMG}-${JDK}-maven:latest /bin/bash -c "cd /mnt; script/ci_build.sh"
